name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para o nome do seu branch principal, se necessário

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Fazer upload dos arquivos
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./src/pages/

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v2
